### ISSUE TITLE
bot_memories folder does not exist

### ISSUE THREAD

**Issue by ghost** [jediknight813/llama-cpp-discord-bot#4]
Traceback (most recent call last):
    File "/home/user/.local/lib/python3.10/site-packages/discord/client.py", line 409, in _run_event
      await coro(*args, **kwargs)
    File "/home/user/Projects/llama-cpp-discord-bot/scripts/main.py", line 91, in on_message
      output = get_llama_response(server_message.content.replace('<@'+str(client.user.id)+'>', ""), current_model, current_bot_personality)
    File "/home/user/Projects/llama-cpp-discord-bot/scripts/utils.py", line 17, in get_llama_response
      chat_history = get_chat_history(current_bot_personality)
    File "/home/bakura/Projects/llama-cpp-discord-bot/scripts/utils.py", line 80, in get_chat_history
      db = TinyDB('./bot_memories/'+current_bot_personality)
    File "/home/user/.local/lib/python3.10/site-packages/tinydb/database.py", line 94, in __init__
      self._storage: Storage = storage(*args, **kwargs)
    File "/home/user/.local/lib/python3.10/site-packages/tinydb/storages.py", line 102, in __init__
      touch(path, create_dirs=create_dirs)
    File "/home/user/.local/lib/python3.10/site-packages/tinydb/storages.py", line 31, in touch
      with open(path, 'a'):
  FileNotFoundError: [Errno 2] No such file or directory: './bot_memories/llamaBot.json'

**Comment by jediknight813** [comment]
Fixed the missing folder issue.
