### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Keepslus** [jediknight813/llama-cpp-discord-bot#7]
[2023-10-14 16:07:40] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\janko\OneDrive\Desktop\VenomGPT\llama-cpp-discord-bot\scripts\main.py", line 22, in on_ready
    await start_up(current_model)
  File "C:\Users\janko\OneDrive\Desktop\VenomGPT\llama-cpp-discord-bot\scripts\utils.py", line 58, in start_up
    command = "python3 -m llama_cpp.server --model "+current_model+"--host 0.0.0.0 --port 8000"
TypeError: can only concatenate str (not "NoneType") to str

**Comment by jediknight813** [comment]
I made some fixes, try pulling the changes and running it again.
