### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zooteld** [jediknight813/llama-cpp-discord-bot#8]
on startup getting an error causing it to not work.

ERROR    discord.client Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/ng/.local/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ng/mapes/mapes.bot/scripts/main.py", line 93, in on_message
    db = TinyDB("./bot_memories/bot_state.json")
  File "/home/ng/.local/lib/python3.10/site-packages/tinydb/database.py", line 94, in __init__
    self._storage: Storage = storage(*args, **kwargs)
  File "/home/ng/.local/lib/python3.10/site-packages/tinydb/storages.py", line 113, in __init__
    touch(path, create_dirs=create_dirs)
  File "/home/ng/.local/lib/python3.10/site-packages/tinydb/storages.py", line 32, in touch
    with open(path, 'a'):
FileNotFoundError: [Errno 2] No such file or directory: './bot_memories/bot_state.json'

**Comment by zooteld** [comment]
I got it working... a lot of your paths in the main.py and utils.py are wrong. they point to ./models and ./bot_personalities when they need to be ../models and ../bot_personalities. it needs that extra "." to find the paths
