### ISSUE TITLE
openai.completion is no longer supported

### ISSUE THREAD

**Issue by AmFerra** [jediknight813/llama-cpp-discord-bot#9]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/src/scripts/main.py", line 97, in on_message
    output = get_llama_response(server_message.content.replace('<@'+str(client.user.id)+'>', ""), current_model, current_bot_personality)
  File "/src/scripts/utils.py", line 27, in get_llama_response
    response = openai.Completion.create(
  File "/usr/local/lib/python3.9/site-packages/openai/_utils/_proxy.py", line 22, in __getattr__
    return getattr(self.__get_proxied__(), attr)
  File "/usr/local/lib/python3.9/site-packages/openai/_utils/_proxy.py", line 43, in __get_proxied__
    return self.__load__()
  File "/usr/local/lib/python3.9/site-packages/openai/lib/_old_api.py", line 33, in __load__
    raise APIRemovedInV1(symbol=self._symbol)
openai.lib._old_api.APIRemovedInV1:

You tried to access openai.Completion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface.

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

**Comment by jediknight813** [comment]
I made some changes, try it now.

**Comment by AmFerra** [comment]
It does work, thanks
